apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: my-app-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shenali-SJ/kube-configs
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp 
  syncPloicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

